[package]
name = "ktra_ui"
version = "0.1.0"
authors = ["Gabriel Smith <ga29smith@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.8.3"
clap = "2.33.3"
curl = "0.4.34"
log = "0.4.0"

[build-dependencies]
vergen = "3.1.0"
